### ISSUE TITLE
 'stddef.h' file not found

### ISSUE THREAD

**Issue by GewoonJaap** [cpp-linter/cpp-linter-action#121] opened 2022-11-05 10:48 UTC
I am trying to run the clang-tidy action however I am getting the following error:

```
INFO:CPP Linter:Running "clang-tidy-12 --export-fixes=clang_tidy_output.yml -checks=boost-*,bugprone-*,performance-*,readability-*,portability-*,modernize-*,clang-analyzer-*,cppcoreguidelines-* --extra-arg= src/main.cpp"
  DEBUG:CPP Linter:Output from clang-tidy:
  /usr/include/wchar.h:35:10: error: 'stddef.h' file not found [clang-diagnostic-error]
  #include <stddef.h>
```
  
  I am not getting this error on my local PC or with any of my GH Actions build scripts, only the clang-tidy action throws this error. How to fix/ignore this?

**Comment by 2bndy5** [comment] 2022-11-05 10:59
We are still trying to understand why this is happening, but we are aware of this.

The only known workaround that we can recommend is to use the [cpp-linter pkg](https://cpp-linter.github.io/cpp-linter) manually via
```
pip install cpp-linter
```
and ensure the version of clang-tidy and/or clang-format is installed before calling the [`cpp-linter` CLI](https://cpp-linter.github.io/cpp-linter/cli_args.html#command-line-interface-options).

**Comment by GewoonJaap** [comment] 2022-11-05 12:46
Currently using @main, but V2 had the same issue. It's strange that one of my repos works fine with the linter while the other one gives this error.

Repo with error has a submodule to the repo thag works and just a hello world file, so nothing exciting there

**Comment by GewoonJaap** [comment] 2022-11-05 12:47
> We are still trying to understand why this is happening, but we are aware of this.
> 
> The only known workaround that we can recommend is to use the [cpp-linter pkg](https://cpp-linter.github.io/cpp-linter) manually via
> 
> ```
> pip install cpp-linter
> ```
> 
> and ensure the version of clang-tidy and/or clang-format is installed before using the [`cpp-linter` CLI](https://cpp-linter.github.io/cpp-linter/cli_args.html#command-line-interface-options).

I will try that in a bit. Any chance you have a GitHub action file I can CTRL + C ;)

**Comment by 2bndy5** [comment] 2022-11-05 12:51
> I will try that in a bit. Any chance you have a GitHub action file I can CTRL + C ;)

Its a bit old (untested for a few months), but it should still work with any runner on github: Try [this code snippet in the README on master](https://github.com/cpp-linter/cpp-linter-action/tree/master#using-the-python-source-code). You'll still have to tweak it for your project (obviously), but its a good start.

**Comment by 2bndy5** [comment] 2022-11-05 12:53
Keep in mind that the Ubuntu runner already comes with v12 of clang tools, so you may only need the stuff specific to `cpp-linter` steps.

**Comment by GewoonJaap** [comment] 2022-11-05 12:54
Thanks! Will try that one out. Just thinking, could it have something to do with git submodules? Because the referenced .h file is only used in one of my submodules. I tried to ignore the entire folder, but it didn't help sadly..

**Comment by 2bndy5** [comment] 2022-11-05 13:02
Like I said we've looked into it and got stumped. This problem has been reported from repos that don't use submodules. Our test repo also uses a submodule, but any submodule's path is automatically ignored by cpp-linter. It wouldn't make sense to tell cpp-linter analyze someone else's project that your using in your repo, although it could be done with the `--ignore` option.

The problem that I see is that clang-tidy doesn't know where to find stddef.h when analyzing any header that includes it in the C std libs. The fact that this doesn't happen locally makes this problem hard to diagnose.

**Comment by 2bndy5** [comment] 2022-11-05 13:06
Its not specific to Ubuntu runners either. Windows runners show the problem too. It does seem to happen more with clang-tidy-12 more than others, but it still does happen with other clang-tidy versions. My best guess is that the runner's C std lib is not the version that clang-tidy was built for (??) 🤷🏼

**Comment by 2bndy5** [comment] 2022-11-05 13:16
We could be a bit more helpful if the repo was public and you provided a link.

**Comment by GewoonJaap** [comment] 2022-11-05 14:11
> 

Sadly the repo is private and I am unable to make it public

**Comment by 2bndy5** [comment] 2022-11-05 14:13
That's unfortunate here but understandable in the bigger picture.

**Comment by ClemensLinnhoff** [comment] 2023-02-03 18:19
I am having the same issue of `'stddef.h' file not found` in various files. You can check out [this](https://github.com/openMSL/reflection_based_lidar_object_model/pull/5), where you will also find the yaml config file.

**Comment by 2bndy5** [comment] 2023-02-03 19:07
This still eludes me... I think it has something to do with certain versions of clang-tidy and the installed C std libs.  A while back, I found a stackoverflow suggestion that recommended using the C std lib from LLVM project (instead of the OS-specific PPA), but I don't think that solution is the right approach here.

**Comment by ClemensLinnhoff** [comment] 2023-02-06 14:36
@GewoonJaap did you find a fix for your private repository? Because with this error the cpp-linter is not really usable as it flags basically every file.

@2bndy5 Additionally we have other problems with the linter. Multiple header files are not found, although the compiler does not have a problem with it and we do a complete build within the pipeline, so that the compile_commands.json can be used. Probably in correlation with this error, some functions are marked as "can be made static" which are already declared static in the corresponding header file. So there seems to be a general problem with finding the correct headers. Do you have any idea how to fix this?

**Comment by 2bndy5** [comment] 2023-02-06 15:13
TBH, our python script doesn't do anything special. It simply finds source files and feeds them to clang-format and/or clang-tidy. The problems you're reporting here sound more like problems with clang-tidy. Since I didn't author anything in the clang project, I can't confidently make any sound suggestions. It would be better to be able to reproduce this locally, but we've been unsuccessful on that front.

That said, have you tried using a different version of clang-tidy? `ubuntu-latest` (currently Ubuntu-22.04) ships with v12, v13, and v14, so I'd recommend trying those because, as I said before, I think this problem is largely related to using certain versions of clang-tidy with certain version of the C/C++ std libs. It should be noted that each major version of the clang project isn't fully backward compatible, so **the specified version is important**.

> Probably in correlation with this error, some functions are marked as "can be made static" which are already declared static in the corresponding header file.

You're PR covers so many files, its not good to assume that the problems are related. In fact, this is the first I'm hearing about this error. My first impression makes me think there's a discrepancy between the implementation file and the header, but IDK.

We currently don't have a plan to support filtering the output captured from clang-tidy, and we cannot support using a special set of rules for certain files (which should be possible with multiple .clang-tidy config files).

---
> Try adding version and setting it to '14' might fix 'stddef.h' file not found

Good catch @shenxianpeng ! If using the native v12 binary is desired, then the version option should specify `12.0.1` which _might_ include the a fix (though I doubt it). The `ubuntu-20.04` runners ship with v12.0.0.

**Comment by ClemensLinnhoff** [comment] 2023-02-06 16:19
Specifying to use clang version 14 did fix the stddef.h error! Thank you for the suggestion!

The other errors remain, but I will try to replicate them offline.

**Comment by 2bndy5** [comment] 2023-02-06 16:21
I'm closing this. Its worth opening a new issue to track the "could be made static" issue.

**Closed by 2bndy5** 2023-02-06 16:21 UTC
Labels: question
